/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WalletRouteImport } from './routes/wallet'
import { Route as TiersRouteImport } from './routes/tiers'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as MealsRouteImport } from './routes/meals'
import { Route as LoginRouteImport } from './routes/login'
import { Route as EliteRouteImport } from './routes/elite'
import { Route as EcosystemRouteImport } from './routes/ecosystem'
import { Route as Chatb2kRouteImport } from './routes/chatb2k'
import { Route as AutopilotRouteImport } from './routes/autopilot'
import { Route as AgentsRouteImport } from './routes/agents'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as Chatb2kIndexRouteImport } from './routes/chatb2k.index'
import { Route as ShopProductIdRouteImport } from './routes/shop.$productId'
import { Route as ProductsSlugRouteImport } from './routes/products.$slug'
import { Route as CheckoutSuccessRouteImport } from './routes/checkout.success'
import { Route as CheckoutCallbackRouteImport } from './routes/checkout.callback'
import { Route as Chatb2kOnboardingRouteImport } from './routes/chatb2k.onboarding'
import { Route as Chatb2kCoachRouteImport } from './routes/chatb2k.coach'
import { Route as AdminRevenueAiRouteImport } from './routes/admin.revenue-ai'
import { Route as ApiPublicPaystackWebhookRouteImport } from './routes/api/public/paystack-webhook'
import { Route as ApiPublicAssetProductIdRouteImport } from './routes/api/public/asset.$productId'

const WalletRoute = WalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const TiersRoute = TiersRouteImport.update({
  id: '/tiers',
  path: '/tiers',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const MealsRoute = MealsRouteImport.update({
  id: '/meals',
  path: '/meals',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EliteRoute = EliteRouteImport.update({
  id: '/elite',
  path: '/elite',
  getParentRoute: () => rootRouteImport,
} as any)
const EcosystemRoute = EcosystemRouteImport.update({
  id: '/ecosystem',
  path: '/ecosystem',
  getParentRoute: () => rootRouteImport,
} as any)
const Chatb2kRoute = Chatb2kRouteImport.update({
  id: '/chatb2k',
  path: '/chatb2k',
  getParentRoute: () => rootRouteImport,
} as any)
const AutopilotRoute = AutopilotRouteImport.update({
  id: '/autopilot',
  path: '/autopilot',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsRoute = AgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const Chatb2kIndexRoute = Chatb2kIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => Chatb2kRoute,
} as any)
const ShopProductIdRoute = ShopProductIdRouteImport.update({
  id: '/$productId',
  path: '/$productId',
  getParentRoute: () => ShopRoute,
} as any)
const ProductsSlugRoute = ProductsSlugRouteImport.update({
  id: '/products/$slug',
  path: '/products/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutSuccessRoute = CheckoutSuccessRouteImport.update({
  id: '/checkout/success',
  path: '/checkout/success',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutCallbackRoute = CheckoutCallbackRouteImport.update({
  id: '/checkout/callback',
  path: '/checkout/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const Chatb2kOnboardingRoute = Chatb2kOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => Chatb2kRoute,
} as any)
const Chatb2kCoachRoute = Chatb2kCoachRouteImport.update({
  id: '/coach',
  path: '/coach',
  getParentRoute: () => Chatb2kRoute,
} as any)
const AdminRevenueAiRoute = AdminRevenueAiRouteImport.update({
  id: '/revenue-ai',
  path: '/revenue-ai',
  getParentRoute: () => AdminRoute,
} as any)
const ApiPublicPaystackWebhookRoute =
  ApiPublicPaystackWebhookRouteImport.update({
    id: '/api/public/paystack-webhook',
    path: '/api/public/paystack-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicAssetProductIdRoute = ApiPublicAssetProductIdRouteImport.update({
  id: '/api/public/asset/$productId',
  path: '/api/public/asset/$productId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/agents': typeof AgentsRoute
  '/autopilot': typeof AutopilotRoute
  '/chatb2k': typeof Chatb2kRouteWithChildren
  '/ecosystem': typeof EcosystemRoute
  '/elite': typeof EliteRoute
  '/login': typeof LoginRoute
  '/meals': typeof MealsRoute
  '/register': typeof RegisterRoute
  '/settings': typeof SettingsRoute
  '/shop': typeof ShopRouteWithChildren
  '/tiers': typeof TiersRoute
  '/wallet': typeof WalletRoute
  '/admin/revenue-ai': typeof AdminRevenueAiRoute
  '/chatb2k/coach': typeof Chatb2kCoachRoute
  '/chatb2k/onboarding': typeof Chatb2kOnboardingRoute
  '/checkout/callback': typeof CheckoutCallbackRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/shop/$productId': typeof ShopProductIdRoute
  '/chatb2k/': typeof Chatb2kIndexRoute
  '/api/public/paystack-webhook': typeof ApiPublicPaystackWebhookRoute
  '/api/public/asset/$productId': typeof ApiPublicAssetProductIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/agents': typeof AgentsRoute
  '/autopilot': typeof AutopilotRoute
  '/ecosystem': typeof EcosystemRoute
  '/elite': typeof EliteRoute
  '/login': typeof LoginRoute
  '/meals': typeof MealsRoute
  '/register': typeof RegisterRoute
  '/settings': typeof SettingsRoute
  '/shop': typeof ShopRouteWithChildren
  '/tiers': typeof TiersRoute
  '/wallet': typeof WalletRoute
  '/admin/revenue-ai': typeof AdminRevenueAiRoute
  '/chatb2k/coach': typeof Chatb2kCoachRoute
  '/chatb2k/onboarding': typeof Chatb2kOnboardingRoute
  '/checkout/callback': typeof CheckoutCallbackRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/shop/$productId': typeof ShopProductIdRoute
  '/chatb2k': typeof Chatb2kIndexRoute
  '/api/public/paystack-webhook': typeof ApiPublicPaystackWebhookRoute
  '/api/public/asset/$productId': typeof ApiPublicAssetProductIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/agents': typeof AgentsRoute
  '/autopilot': typeof AutopilotRoute
  '/chatb2k': typeof Chatb2kRouteWithChildren
  '/ecosystem': typeof EcosystemRoute
  '/elite': typeof EliteRoute
  '/login': typeof LoginRoute
  '/meals': typeof MealsRoute
  '/register': typeof RegisterRoute
  '/settings': typeof SettingsRoute
  '/shop': typeof ShopRouteWithChildren
  '/tiers': typeof TiersRoute
  '/wallet': typeof WalletRoute
  '/admin/revenue-ai': typeof AdminRevenueAiRoute
  '/chatb2k/coach': typeof Chatb2kCoachRoute
  '/chatb2k/onboarding': typeof Chatb2kOnboardingRoute
  '/checkout/callback': typeof CheckoutCallbackRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/shop/$productId': typeof ShopProductIdRoute
  '/chatb2k/': typeof Chatb2kIndexRoute
  '/api/public/paystack-webhook': typeof ApiPublicPaystackWebhookRoute
  '/api/public/asset/$productId': typeof ApiPublicAssetProductIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/agents'
    | '/autopilot'
    | '/chatb2k'
    | '/ecosystem'
    | '/elite'
    | '/login'
    | '/meals'
    | '/register'
    | '/settings'
    | '/shop'
    | '/tiers'
    | '/wallet'
    | '/admin/revenue-ai'
    | '/chatb2k/coach'
    | '/chatb2k/onboarding'
    | '/checkout/callback'
    | '/checkout/success'
    | '/products/$slug'
    | '/shop/$productId'
    | '/chatb2k/'
    | '/api/public/paystack-webhook'
    | '/api/public/asset/$productId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/agents'
    | '/autopilot'
    | '/ecosystem'
    | '/elite'
    | '/login'
    | '/meals'
    | '/register'
    | '/settings'
    | '/shop'
    | '/tiers'
    | '/wallet'
    | '/admin/revenue-ai'
    | '/chatb2k/coach'
    | '/chatb2k/onboarding'
    | '/checkout/callback'
    | '/checkout/success'
    | '/products/$slug'
    | '/shop/$productId'
    | '/chatb2k'
    | '/api/public/paystack-webhook'
    | '/api/public/asset/$productId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/agents'
    | '/autopilot'
    | '/chatb2k'
    | '/ecosystem'
    | '/elite'
    | '/login'
    | '/meals'
    | '/register'
    | '/settings'
    | '/shop'
    | '/tiers'
    | '/wallet'
    | '/admin/revenue-ai'
    | '/chatb2k/coach'
    | '/chatb2k/onboarding'
    | '/checkout/callback'
    | '/checkout/success'
    | '/products/$slug'
    | '/shop/$productId'
    | '/chatb2k/'
    | '/api/public/paystack-webhook'
    | '/api/public/asset/$productId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AgentsRoute: typeof AgentsRoute
  AutopilotRoute: typeof AutopilotRoute
  Chatb2kRoute: typeof Chatb2kRouteWithChildren
  EcosystemRoute: typeof EcosystemRoute
  EliteRoute: typeof EliteRoute
  LoginRoute: typeof LoginRoute
  MealsRoute: typeof MealsRoute
  RegisterRoute: typeof RegisterRoute
  SettingsRoute: typeof SettingsRoute
  ShopRoute: typeof ShopRouteWithChildren
  TiersRoute: typeof TiersRoute
  WalletRoute: typeof WalletRoute
  CheckoutCallbackRoute: typeof CheckoutCallbackRoute
  CheckoutSuccessRoute: typeof CheckoutSuccessRoute
  ProductsSlugRoute: typeof ProductsSlugRoute
  ApiPublicPaystackWebhookRoute: typeof ApiPublicPaystackWebhookRoute
  ApiPublicAssetProductIdRoute: typeof ApiPublicAssetProductIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tiers': {
      id: '/tiers'
      path: '/tiers'
      fullPath: '/tiers'
      preLoaderRoute: typeof TiersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meals': {
      id: '/meals'
      path: '/meals'
      fullPath: '/meals'
      preLoaderRoute: typeof MealsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/elite': {
      id: '/elite'
      path: '/elite'
      fullPath: '/elite'
      preLoaderRoute: typeof EliteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ecosystem': {
      id: '/ecosystem'
      path: '/ecosystem'
      fullPath: '/ecosystem'
      preLoaderRoute: typeof EcosystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chatb2k': {
      id: '/chatb2k'
      path: '/chatb2k'
      fullPath: '/chatb2k'
      preLoaderRoute: typeof Chatb2kRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/autopilot': {
      id: '/autopilot'
      path: '/autopilot'
      fullPath: '/autopilot'
      preLoaderRoute: typeof AutopilotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents': {
      id: '/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chatb2k/': {
      id: '/chatb2k/'
      path: '/'
      fullPath: '/chatb2k/'
      preLoaderRoute: typeof Chatb2kIndexRouteImport
      parentRoute: typeof Chatb2kRoute
    }
    '/shop/$productId': {
      id: '/shop/$productId'
      path: '/$productId'
      fullPath: '/shop/$productId'
      preLoaderRoute: typeof ShopProductIdRouteImport
      parentRoute: typeof ShopRoute
    }
    '/products/$slug': {
      id: '/products/$slug'
      path: '/products/$slug'
      fullPath: '/products/$slug'
      preLoaderRoute: typeof ProductsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/success': {
      id: '/checkout/success'
      path: '/checkout/success'
      fullPath: '/checkout/success'
      preLoaderRoute: typeof CheckoutSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/callback': {
      id: '/checkout/callback'
      path: '/checkout/callback'
      fullPath: '/checkout/callback'
      preLoaderRoute: typeof CheckoutCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chatb2k/onboarding': {
      id: '/chatb2k/onboarding'
      path: '/onboarding'
      fullPath: '/chatb2k/onboarding'
      preLoaderRoute: typeof Chatb2kOnboardingRouteImport
      parentRoute: typeof Chatb2kRoute
    }
    '/chatb2k/coach': {
      id: '/chatb2k/coach'
      path: '/coach'
      fullPath: '/chatb2k/coach'
      preLoaderRoute: typeof Chatb2kCoachRouteImport
      parentRoute: typeof Chatb2kRoute
    }
    '/admin/revenue-ai': {
      id: '/admin/revenue-ai'
      path: '/revenue-ai'
      fullPath: '/admin/revenue-ai'
      preLoaderRoute: typeof AdminRevenueAiRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/public/paystack-webhook': {
      id: '/api/public/paystack-webhook'
      path: '/api/public/paystack-webhook'
      fullPath: '/api/public/paystack-webhook'
      preLoaderRoute: typeof ApiPublicPaystackWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/asset/$productId': {
      id: '/api/public/asset/$productId'
      path: '/api/public/asset/$productId'
      fullPath: '/api/public/asset/$productId'
      preLoaderRoute: typeof ApiPublicAssetProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminRevenueAiRoute: typeof AdminRevenueAiRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminRevenueAiRoute: AdminRevenueAiRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface Chatb2kRouteChildren {
  Chatb2kCoachRoute: typeof Chatb2kCoachRoute
  Chatb2kOnboardingRoute: typeof Chatb2kOnboardingRoute
  Chatb2kIndexRoute: typeof Chatb2kIndexRoute
}

const Chatb2kRouteChildren: Chatb2kRouteChildren = {
  Chatb2kCoachRoute: Chatb2kCoachRoute,
  Chatb2kOnboardingRoute: Chatb2kOnboardingRoute,
  Chatb2kIndexRoute: Chatb2kIndexRoute,
}

const Chatb2kRouteWithChildren =
  Chatb2kRoute._addFileChildren(Chatb2kRouteChildren)

interface ShopRouteChildren {
  ShopProductIdRoute: typeof ShopProductIdRoute
}

const ShopRouteChildren: ShopRouteChildren = {
  ShopProductIdRoute: ShopProductIdRoute,
}

const ShopRouteWithChildren = ShopRoute._addFileChildren(ShopRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AgentsRoute: AgentsRoute,
  AutopilotRoute: AutopilotRoute,
  Chatb2kRoute: Chatb2kRouteWithChildren,
  EcosystemRoute: EcosystemRoute,
  EliteRoute: EliteRoute,
  LoginRoute: LoginRoute,
  MealsRoute: MealsRoute,
  RegisterRoute: RegisterRoute,
  SettingsRoute: SettingsRoute,
  ShopRoute: ShopRouteWithChildren,
  TiersRoute: TiersRoute,
  WalletRoute: WalletRoute,
  CheckoutCallbackRoute: CheckoutCallbackRoute,
  CheckoutSuccessRoute: CheckoutSuccessRoute,
  ProductsSlugRoute: ProductsSlugRoute,
  ApiPublicPaystackWebhookRoute: ApiPublicPaystackWebhookRoute,
  ApiPublicAssetProductIdRoute: ApiPublicAssetProductIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
