/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AgentsRouteImport } from './routes/agents'
import { Route as AutopilotRouteImport } from './routes/autopilot'
import { Route as Chatb2kRouteImport } from './routes/chatb2k'
import { Route as EcosystemRouteImport } from './routes/ecosystem'
import { Route as EliteRouteImport } from './routes/elite'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MealsRouteImport } from './routes/meals'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TiersRouteImport } from './routes/tiers'
import { Route as WalletRouteImport } from './routes/wallet'
import { Route as AdminCatalogRouteImport } from './routes/admin.catalog'
import { Route as AdminMediaRouteImport } from './routes/admin.media'
import { Route as AdminRevenueAiRouteImport } from './routes/admin.revenue-ai'
import { Route as Chatb2kIndexRouteImport } from './routes/chatb2k.index'
import { Route as Chatb2kCeoRouteImport } from './routes/chatb2k.ceo'
import { Route as Chatb2kCoachRouteImport } from './routes/chatb2k.coach'
import { Route as Chatb2kHabitsRouteImport } from './routes/chatb2k.habits'
import { Route as Chatb2kMealsRouteImport } from './routes/chatb2k.meals'
import { Route as Chatb2kOnboardingRouteImport } from './routes/chatb2k.onboarding'
import { Route as Chatb2kWorkoutsRouteImport } from './routes/chatb2k.workouts'
import { Route as CheckoutCallbackRouteImport } from './routes/checkout.callback'
import { Route as CheckoutSuccessRouteImport } from './routes/checkout.success'
import { Route as CollectionsIndexRouteImport } from './routes/collections.index'
import { Route as CollectionsCodeRouteImport } from './routes/collections.$code'
import { Route as ProductsSlugRouteImport } from './routes/products.$slug'
import { Route as ShopProductIdRouteImport } from './routes/shop.$productId'
import { Route as ApiPublicPaystackWebhookRouteImport } from './routes/api/public/paystack-webhook'
import { Route as ApiPublicAssetProductIdRouteImport } from './routes/api/public/asset.$productId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsRoute = AgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const AutopilotRoute = AutopilotRouteImport.update({
  id: '/autopilot',
  path: '/autopilot',
  getParentRoute: () => rootRouteImport,
} as any)
const Chatb2kRoute = Chatb2kRouteImport.update({
  id: '/chatb2k',
  path: '/chatb2k',
  getParentRoute: () => rootRouteImport,
} as any)
const EcosystemRoute = EcosystemRouteImport.update({
  id: '/ecosystem',
  path: '/ecosystem',
  getParentRoute: () => rootRouteImport,
} as any)
const EliteRoute = EliteRouteImport.update({
  id: '/elite',
  path: '/elite',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MealsRoute = MealsRouteImport.update({
  id: '/meals',
  path: '/meals',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TiersRoute = TiersRouteImport.update({
  id: '/tiers',
  path: '/tiers',
  getParentRoute: () => rootRouteImport,
} as any)
const WalletRoute = WalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCatalogRoute = AdminCatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMediaRoute = AdminMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRevenueAiRoute = AdminRevenueAiRouteImport.update({
  id: '/revenue-ai',
  path: '/revenue-ai',
  getParentRoute: () => AdminRoute,
} as any)
const Chatb2kIndexRoute = Chatb2kIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => Chatb2kRoute,
} as any)
const Chatb2kCeoRoute = Chatb2kCeoRouteImport.update({
  id: '/ceo',
  path: '/ceo',
  getParentRoute: () => Chatb2kRoute,
} as any)
const Chatb2kCoachRoute = Chatb2kCoachRouteImport.update({
  id: '/coach',
  path: '/coach',
  getParentRoute: () => Chatb2kRoute,
} as any)
const Chatb2kHabitsRoute = Chatb2kHabitsRouteImport.update({
  id: '/habits',
  path: '/habits',
  getParentRoute: () => Chatb2kRoute,
} as any)
const Chatb2kMealsRoute = Chatb2kMealsRouteImport.update({
  id: '/meals',
  path: '/meals',
  getParentRoute: () => Chatb2kRoute,
} as any)
const Chatb2kOnboardingRoute = Chatb2kOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => Chatb2kRoute,
} as any)
const Chatb2kWorkoutsRoute = Chatb2kWorkoutsRouteImport.update({
  id: '/workouts',
  path: '/workouts',
  getParentRoute: () => Chatb2kRoute,
} as any)
const CheckoutCallbackRoute = CheckoutCallbackRouteImport.update({
  id: '/checkout/callback',
  path: '/checkout/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutSuccessRoute = CheckoutSuccessRouteImport.update({
  id: '/checkout/success',
  path: '/checkout/success',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsIndexRoute = CollectionsIndexRouteImport.update({
  id: '/collections/',
  path: '/collections/',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsCodeRoute = CollectionsCodeRouteImport.update({
  id: '/collections/$code',
  path: '/collections/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsSlugRoute = ProductsSlugRouteImport.update({
  id: '/products/$slug',
  path: '/products/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopProductIdRoute = ShopProductIdRouteImport.update({
  id: '/$productId',
  path: '/$productId',
  getParentRoute: () => ShopRoute,
} as any)
const ApiPublicPaystackWebhookRoute =
  ApiPublicPaystackWebhookRouteImport.update({
    id: '/api/public/paystack-webhook',
    path: '/api/public/paystack-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicAssetProductIdRoute = ApiPublicAssetProductIdRouteImport.update({
  id: '/api/public/asset/$productId',
  path: '/api/public/asset/$productId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/agents': typeof AgentsRoute
  '/autopilot': typeof AutopilotRoute
  '/chatb2k': typeof Chatb2kRouteWithChildren
  '/ecosystem': typeof EcosystemRoute
  '/elite': typeof EliteRoute
  '/login': typeof LoginRoute
  '/meals': typeof MealsRoute
  '/register': typeof RegisterRoute
  '/settings': typeof SettingsRoute
  '/shop': typeof ShopRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tiers': typeof TiersRoute
  '/wallet': typeof WalletRoute
  '/admin/catalog': typeof AdminCatalogRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/revenue-ai': typeof AdminRevenueAiRoute
  '/chatb2k/ceo': typeof Chatb2kCeoRoute
  '/chatb2k/coach': typeof Chatb2kCoachRoute
  '/chatb2k/habits': typeof Chatb2kHabitsRoute
  '/chatb2k/meals': typeof Chatb2kMealsRoute
  '/chatb2k/onboarding': typeof Chatb2kOnboardingRoute
  '/chatb2k/workouts': typeof Chatb2kWorkoutsRoute
  '/checkout/callback': typeof CheckoutCallbackRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/collections/$code': typeof CollectionsCodeRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/shop/$productId': typeof ShopProductIdRoute
  '/chatb2k/': typeof Chatb2kIndexRoute
  '/collections/': typeof CollectionsIndexRoute
  '/api/public/paystack-webhook': typeof ApiPublicPaystackWebhookRoute
  '/api/public/asset/$productId': typeof ApiPublicAssetProductIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/agents': typeof AgentsRoute
  '/autopilot': typeof AutopilotRoute
  '/ecosystem': typeof EcosystemRoute
  '/elite': typeof EliteRoute
  '/login': typeof LoginRoute
  '/meals': typeof MealsRoute
  '/register': typeof RegisterRoute
  '/settings': typeof SettingsRoute
  '/shop': typeof ShopRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tiers': typeof TiersRoute
  '/wallet': typeof WalletRoute
  '/admin/catalog': typeof AdminCatalogRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/revenue-ai': typeof AdminRevenueAiRoute
  '/chatb2k/ceo': typeof Chatb2kCeoRoute
  '/chatb2k/coach': typeof Chatb2kCoachRoute
  '/chatb2k/habits': typeof Chatb2kHabitsRoute
  '/chatb2k/meals': typeof Chatb2kMealsRoute
  '/chatb2k/onboarding': typeof Chatb2kOnboardingRoute
  '/chatb2k/workouts': typeof Chatb2kWorkoutsRoute
  '/checkout/callback': typeof CheckoutCallbackRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/collections/$code': typeof CollectionsCodeRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/shop/$productId': typeof ShopProductIdRoute
  '/chatb2k': typeof Chatb2kIndexRoute
  '/collections': typeof CollectionsIndexRoute
  '/api/public/paystack-webhook': typeof ApiPublicPaystackWebhookRoute
  '/api/public/asset/$productId': typeof ApiPublicAssetProductIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/agents': typeof AgentsRoute
  '/autopilot': typeof AutopilotRoute
  '/chatb2k': typeof Chatb2kRouteWithChildren
  '/ecosystem': typeof EcosystemRoute
  '/elite': typeof EliteRoute
  '/login': typeof LoginRoute
  '/meals': typeof MealsRoute
  '/register': typeof RegisterRoute
  '/settings': typeof SettingsRoute
  '/shop': typeof ShopRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tiers': typeof TiersRoute
  '/wallet': typeof WalletRoute
  '/admin/catalog': typeof AdminCatalogRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/revenue-ai': typeof AdminRevenueAiRoute
  '/chatb2k/ceo': typeof Chatb2kCeoRoute
  '/chatb2k/coach': typeof Chatb2kCoachRoute
  '/chatb2k/habits': typeof Chatb2kHabitsRoute
  '/chatb2k/meals': typeof Chatb2kMealsRoute
  '/chatb2k/onboarding': typeof Chatb2kOnboardingRoute
  '/chatb2k/workouts': typeof Chatb2kWorkoutsRoute
  '/checkout/callback': typeof CheckoutCallbackRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/collections/$code': typeof CollectionsCodeRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/shop/$productId': typeof ShopProductIdRoute
  '/chatb2k/': typeof Chatb2kIndexRoute
  '/collections/': typeof CollectionsIndexRoute
  '/api/public/paystack-webhook': typeof ApiPublicPaystackWebhookRoute
  '/api/public/asset/$productId': typeof ApiPublicAssetProductIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/agents'
    | '/autopilot'
    | '/chatb2k'
    | '/ecosystem'
    | '/elite'
    | '/login'
    | '/meals'
    | '/register'
    | '/settings'
    | '/shop'
    | '/sitemap.xml'
    | '/tiers'
    | '/wallet'
    | '/admin/catalog'
    | '/admin/media'
    | '/admin/revenue-ai'
    | '/chatb2k/ceo'
    | '/chatb2k/coach'
    | '/chatb2k/habits'
    | '/chatb2k/meals'
    | '/chatb2k/onboarding'
    | '/chatb2k/workouts'
    | '/checkout/callback'
    | '/checkout/success'
    | '/collections/$code'
    | '/products/$slug'
    | '/shop/$productId'
    | '/chatb2k/'
    | '/collections/'
    | '/api/public/paystack-webhook'
    | '/api/public/asset/$productId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/agents'
    | '/autopilot'
    | '/ecosystem'
    | '/elite'
    | '/login'
    | '/meals'
    | '/register'
    | '/settings'
    | '/shop'
    | '/sitemap.xml'
    | '/tiers'
    | '/wallet'
    | '/admin/catalog'
    | '/admin/media'
    | '/admin/revenue-ai'
    | '/chatb2k/ceo'
    | '/chatb2k/coach'
    | '/chatb2k/habits'
    | '/chatb2k/meals'
    | '/chatb2k/onboarding'
    | '/chatb2k/workouts'
    | '/checkout/callback'
    | '/checkout/success'
    | '/collections/$code'
    | '/products/$slug'
    | '/shop/$productId'
    | '/chatb2k'
    | '/collections'
    | '/api/public/paystack-webhook'
    | '/api/public/asset/$productId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/agents'
    | '/autopilot'
    | '/chatb2k'
    | '/ecosystem'
    | '/elite'
    | '/login'
    | '/meals'
    | '/register'
    | '/settings'
    | '/shop'
    | '/sitemap.xml'
    | '/tiers'
    | '/wallet'
    | '/admin/catalog'
    | '/admin/media'
    | '/admin/revenue-ai'
    | '/chatb2k/ceo'
    | '/chatb2k/coach'
    | '/chatb2k/habits'
    | '/chatb2k/meals'
    | '/chatb2k/onboarding'
    | '/chatb2k/workouts'
    | '/checkout/callback'
    | '/checkout/success'
    | '/collections/$code'
    | '/products/$slug'
    | '/shop/$productId'
    | '/chatb2k/'
    | '/collections/'
    | '/api/public/paystack-webhook'
    | '/api/public/asset/$productId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AgentsRoute: typeof AgentsRoute
  AutopilotRoute: typeof AutopilotRoute
  Chatb2kRoute: typeof Chatb2kRouteWithChildren
  EcosystemRoute: typeof EcosystemRoute
  EliteRoute: typeof EliteRoute
  LoginRoute: typeof LoginRoute
  MealsRoute: typeof MealsRoute
  RegisterRoute: typeof RegisterRoute
  SettingsRoute: typeof SettingsRoute
  ShopRoute: typeof ShopRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TiersRoute: typeof TiersRoute
  WalletRoute: typeof WalletRoute
  CheckoutCallbackRoute: typeof CheckoutCallbackRoute
  CheckoutSuccessRoute: typeof CheckoutSuccessRoute
  CollectionsCodeRoute: typeof CollectionsCodeRoute
  ProductsSlugRoute: typeof ProductsSlugRoute
  CollectionsIndexRoute: typeof CollectionsIndexRoute
  ApiPublicPaystackWebhookRoute: typeof ApiPublicPaystackWebhookRoute
  ApiPublicAssetProductIdRoute: typeof ApiPublicAssetProductIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents': {
      id: '/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/autopilot': {
      id: '/autopilot'
      path: '/autopilot'
      fullPath: '/autopilot'
      preLoaderRoute: typeof AutopilotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chatb2k': {
      id: '/chatb2k'
      path: '/chatb2k'
      fullPath: '/chatb2k'
      preLoaderRoute: typeof Chatb2kRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ecosystem': {
      id: '/ecosystem'
      path: '/ecosystem'
      fullPath: '/ecosystem'
      preLoaderRoute: typeof EcosystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/elite': {
      id: '/elite'
      path: '/elite'
      fullPath: '/elite'
      preLoaderRoute: typeof EliteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meals': {
      id: '/meals'
      path: '/meals'
      fullPath: '/meals'
      preLoaderRoute: typeof MealsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tiers': {
      id: '/tiers'
      path: '/tiers'
      fullPath: '/tiers'
      preLoaderRoute: typeof TiersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/catalog': {
      id: '/admin/catalog'
      path: '/catalog'
      fullPath: '/admin/catalog'
      preLoaderRoute: typeof AdminCatalogRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/media': {
      id: '/admin/media'
      path: '/media'
      fullPath: '/admin/media'
      preLoaderRoute: typeof AdminMediaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/revenue-ai': {
      id: '/admin/revenue-ai'
      path: '/revenue-ai'
      fullPath: '/admin/revenue-ai'
      preLoaderRoute: typeof AdminRevenueAiRouteImport
      parentRoute: typeof AdminRoute
    }
    '/chatb2k/': {
      id: '/chatb2k/'
      path: '/'
      fullPath: '/chatb2k/'
      preLoaderRoute: typeof Chatb2kIndexRouteImport
      parentRoute: typeof Chatb2kRoute
    }
    '/chatb2k/ceo': {
      id: '/chatb2k/ceo'
      path: '/ceo'
      fullPath: '/chatb2k/ceo'
      preLoaderRoute: typeof Chatb2kCeoRouteImport
      parentRoute: typeof Chatb2kRoute
    }
    '/chatb2k/coach': {
      id: '/chatb2k/coach'
      path: '/coach'
      fullPath: '/chatb2k/coach'
      preLoaderRoute: typeof Chatb2kCoachRouteImport
      parentRoute: typeof Chatb2kRoute
    }
    '/chatb2k/habits': {
      id: '/chatb2k/habits'
      path: '/habits'
      fullPath: '/chatb2k/habits'
      preLoaderRoute: typeof Chatb2kHabitsRouteImport
      parentRoute: typeof Chatb2kRoute
    }
    '/chatb2k/meals': {
      id: '/chatb2k/meals'
      path: '/meals'
      fullPath: '/chatb2k/meals'
      preLoaderRoute: typeof Chatb2kMealsRouteImport
      parentRoute: typeof Chatb2kRoute
    }
    '/chatb2k/onboarding': {
      id: '/chatb2k/onboarding'
      path: '/onboarding'
      fullPath: '/chatb2k/onboarding'
      preLoaderRoute: typeof Chatb2kOnboardingRouteImport
      parentRoute: typeof Chatb2kRoute
    }
    '/chatb2k/workouts': {
      id: '/chatb2k/workouts'
      path: '/workouts'
      fullPath: '/chatb2k/workouts'
      preLoaderRoute: typeof Chatb2kWorkoutsRouteImport
      parentRoute: typeof Chatb2kRoute
    }
    '/checkout/callback': {
      id: '/checkout/callback'
      path: '/checkout/callback'
      fullPath: '/checkout/callback'
      preLoaderRoute: typeof CheckoutCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/success': {
      id: '/checkout/success'
      path: '/checkout/success'
      fullPath: '/checkout/success'
      preLoaderRoute: typeof CheckoutSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/': {
      id: '/collections/'
      path: '/collections'
      fullPath: '/collections/'
      preLoaderRoute: typeof CollectionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/$code': {
      id: '/collections/$code'
      path: '/collections/$code'
      fullPath: '/collections/$code'
      preLoaderRoute: typeof CollectionsCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$slug': {
      id: '/products/$slug'
      path: '/products/$slug'
      fullPath: '/products/$slug'
      preLoaderRoute: typeof ProductsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/$productId': {
      id: '/shop/$productId'
      path: '/$productId'
      fullPath: '/shop/$productId'
      preLoaderRoute: typeof ShopProductIdRouteImport
      parentRoute: typeof ShopRoute
    }
    '/api/public/paystack-webhook': {
      id: '/api/public/paystack-webhook'
      path: '/api/public/paystack-webhook'
      fullPath: '/api/public/paystack-webhook'
      preLoaderRoute: typeof ApiPublicPaystackWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/asset/$productId': {
      id: '/api/public/asset/$productId'
      path: '/api/public/asset/$productId'
      fullPath: '/api/public/asset/$productId'
      preLoaderRoute: typeof ApiPublicAssetProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminCatalogRoute: typeof AdminCatalogRoute
  AdminMediaRoute: typeof AdminMediaRoute
  AdminRevenueAiRoute: typeof AdminRevenueAiRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCatalogRoute: AdminCatalogRoute,
  AdminMediaRoute: AdminMediaRoute,
  AdminRevenueAiRoute: AdminRevenueAiRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface Chatb2kRouteChildren {
  Chatb2kCeoRoute: typeof Chatb2kCeoRoute
  Chatb2kCoachRoute: typeof Chatb2kCoachRoute
  Chatb2kHabitsRoute: typeof Chatb2kHabitsRoute
  Chatb2kMealsRoute: typeof Chatb2kMealsRoute
  Chatb2kOnboardingRoute: typeof Chatb2kOnboardingRoute
  Chatb2kWorkoutsRoute: typeof Chatb2kWorkoutsRoute
  Chatb2kIndexRoute: typeof Chatb2kIndexRoute
}

const Chatb2kRouteChildren: Chatb2kRouteChildren = {
  Chatb2kCeoRoute: Chatb2kCeoRoute,
  Chatb2kCoachRoute: Chatb2kCoachRoute,
  Chatb2kHabitsRoute: Chatb2kHabitsRoute,
  Chatb2kMealsRoute: Chatb2kMealsRoute,
  Chatb2kOnboardingRoute: Chatb2kOnboardingRoute,
  Chatb2kWorkoutsRoute: Chatb2kWorkoutsRoute,
  Chatb2kIndexRoute: Chatb2kIndexRoute,
}

const Chatb2kRouteWithChildren =
  Chatb2kRoute._addFileChildren(Chatb2kRouteChildren)

interface ShopRouteChildren {
  ShopProductIdRoute: typeof ShopProductIdRoute
}

const ShopRouteChildren: ShopRouteChildren = {
  ShopProductIdRoute: ShopProductIdRoute,
}

const ShopRouteWithChildren = ShopRoute._addFileChildren(ShopRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AgentsRoute: AgentsRoute,
  AutopilotRoute: AutopilotRoute,
  Chatb2kRoute: Chatb2kRouteWithChildren,
  EcosystemRoute: EcosystemRoute,
  EliteRoute: EliteRoute,
  LoginRoute: LoginRoute,
  MealsRoute: MealsRoute,
  RegisterRoute: RegisterRoute,
  SettingsRoute: SettingsRoute,
  ShopRoute: ShopRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TiersRoute: TiersRoute,
  WalletRoute: WalletRoute,
  CheckoutCallbackRoute: CheckoutCallbackRoute,
  CheckoutSuccessRoute: CheckoutSuccessRoute,
  CollectionsCodeRoute: CollectionsCodeRoute,
  ProductsSlugRoute: ProductsSlugRoute,
  CollectionsIndexRoute: CollectionsIndexRoute,
  ApiPublicPaystackWebhookRoute: ApiPublicPaystackWebhookRoute,
  ApiPublicAssetProductIdRoute: ApiPublicAssetProductIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
