/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WalletRouteImport } from './routes/wallet'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as MealsRouteImport } from './routes/meals'
import { Route as LoginRouteImport } from './routes/login'
import { Route as EliteRouteImport } from './routes/elite'
import { Route as EcosystemRouteImport } from './routes/ecosystem'
import { Route as AutopilotRouteImport } from './routes/autopilot'
import { Route as AgentsRouteImport } from './routes/agents'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShopProductIdRouteImport } from './routes/shop.$productId'
import { Route as CheckoutSuccessRouteImport } from './routes/checkout.success'
import { Route as CheckoutCallbackRouteImport } from './routes/checkout.callback'
import { Route as AdminRevenueAiRouteImport } from './routes/admin.revenue-ai'
import { Route as ApiPublicPaystackWebhookRouteImport } from './routes/api/public/paystack-webhook'
import { Route as ApiPublicAssetProductIdRouteImport } from './routes/api/public/asset.$productId'

const WalletRoute = WalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const MealsRoute = MealsRouteImport.update({
  id: '/meals',
  path: '/meals',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EliteRoute = EliteRouteImport.update({
  id: '/elite',
  path: '/elite',
  getParentRoute: () => rootRouteImport,
} as any)
const EcosystemRoute = EcosystemRouteImport.update({
  id: '/ecosystem',
  path: '/ecosystem',
  getParentRoute: () => rootRouteImport,
} as any)
const AutopilotRoute = AutopilotRouteImport.update({
  id: '/autopilot',
  path: '/autopilot',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsRoute = AgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopProductIdRoute = ShopProductIdRouteImport.update({
  id: '/$productId',
  path: '/$productId',
  getParentRoute: () => ShopRoute,
} as any)
const CheckoutSuccessRoute = CheckoutSuccessRouteImport.update({
  id: '/checkout/success',
  path: '/checkout/success',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutCallbackRoute = CheckoutCallbackRouteImport.update({
  id: '/checkout/callback',
  path: '/checkout/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRevenueAiRoute = AdminRevenueAiRouteImport.update({
  id: '/revenue-ai',
  path: '/revenue-ai',
  getParentRoute: () => AdminRoute,
} as any)
const ApiPublicPaystackWebhookRoute =
  ApiPublicPaystackWebhookRouteImport.update({
    id: '/api/public/paystack-webhook',
    path: '/api/public/paystack-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicAssetProductIdRoute = ApiPublicAssetProductIdRouteImport.update({
  id: '/api/public/asset/$productId',
  path: '/api/public/asset/$productId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/agents': typeof AgentsRoute
  '/autopilot': typeof AutopilotRoute
  '/ecosystem': typeof EcosystemRoute
  '/elite': typeof EliteRoute
  '/login': typeof LoginRoute
  '/meals': typeof MealsRoute
  '/register': typeof RegisterRoute
  '/settings': typeof SettingsRoute
  '/shop': typeof ShopRouteWithChildren
  '/wallet': typeof WalletRoute
  '/admin/revenue-ai': typeof AdminRevenueAiRoute
  '/checkout/callback': typeof CheckoutCallbackRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/shop/$productId': typeof ShopProductIdRoute
  '/api/public/paystack-webhook': typeof ApiPublicPaystackWebhookRoute
  '/api/public/asset/$productId': typeof ApiPublicAssetProductIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/agents': typeof AgentsRoute
  '/autopilot': typeof AutopilotRoute
  '/ecosystem': typeof EcosystemRoute
  '/elite': typeof EliteRoute
  '/login': typeof LoginRoute
  '/meals': typeof MealsRoute
  '/register': typeof RegisterRoute
  '/settings': typeof SettingsRoute
  '/shop': typeof ShopRouteWithChildren
  '/wallet': typeof WalletRoute
  '/admin/revenue-ai': typeof AdminRevenueAiRoute
  '/checkout/callback': typeof CheckoutCallbackRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/shop/$productId': typeof ShopProductIdRoute
  '/api/public/paystack-webhook': typeof ApiPublicPaystackWebhookRoute
  '/api/public/asset/$productId': typeof ApiPublicAssetProductIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/agents': typeof AgentsRoute
  '/autopilot': typeof AutopilotRoute
  '/ecosystem': typeof EcosystemRoute
  '/elite': typeof EliteRoute
  '/login': typeof LoginRoute
  '/meals': typeof MealsRoute
  '/register': typeof RegisterRoute
  '/settings': typeof SettingsRoute
  '/shop': typeof ShopRouteWithChildren
  '/wallet': typeof WalletRoute
  '/admin/revenue-ai': typeof AdminRevenueAiRoute
  '/checkout/callback': typeof CheckoutCallbackRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/shop/$productId': typeof ShopProductIdRoute
  '/api/public/paystack-webhook': typeof ApiPublicPaystackWebhookRoute
  '/api/public/asset/$productId': typeof ApiPublicAssetProductIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/agents'
    | '/autopilot'
    | '/ecosystem'
    | '/elite'
    | '/login'
    | '/meals'
    | '/register'
    | '/settings'
    | '/shop'
    | '/wallet'
    | '/admin/revenue-ai'
    | '/checkout/callback'
    | '/checkout/success'
    | '/shop/$productId'
    | '/api/public/paystack-webhook'
    | '/api/public/asset/$productId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/agents'
    | '/autopilot'
    | '/ecosystem'
    | '/elite'
    | '/login'
    | '/meals'
    | '/register'
    | '/settings'
    | '/shop'
    | '/wallet'
    | '/admin/revenue-ai'
    | '/checkout/callback'
    | '/checkout/success'
    | '/shop/$productId'
    | '/api/public/paystack-webhook'
    | '/api/public/asset/$productId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/agents'
    | '/autopilot'
    | '/ecosystem'
    | '/elite'
    | '/login'
    | '/meals'
    | '/register'
    | '/settings'
    | '/shop'
    | '/wallet'
    | '/admin/revenue-ai'
    | '/checkout/callback'
    | '/checkout/success'
    | '/shop/$productId'
    | '/api/public/paystack-webhook'
    | '/api/public/asset/$productId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AgentsRoute: typeof AgentsRoute
  AutopilotRoute: typeof AutopilotRoute
  EcosystemRoute: typeof EcosystemRoute
  EliteRoute: typeof EliteRoute
  LoginRoute: typeof LoginRoute
  MealsRoute: typeof MealsRoute
  RegisterRoute: typeof RegisterRoute
  SettingsRoute: typeof SettingsRoute
  ShopRoute: typeof ShopRouteWithChildren
  WalletRoute: typeof WalletRoute
  CheckoutCallbackRoute: typeof CheckoutCallbackRoute
  CheckoutSuccessRoute: typeof CheckoutSuccessRoute
  ApiPublicPaystackWebhookRoute: typeof ApiPublicPaystackWebhookRoute
  ApiPublicAssetProductIdRoute: typeof ApiPublicAssetProductIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meals': {
      id: '/meals'
      path: '/meals'
      fullPath: '/meals'
      preLoaderRoute: typeof MealsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/elite': {
      id: '/elite'
      path: '/elite'
      fullPath: '/elite'
      preLoaderRoute: typeof EliteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ecosystem': {
      id: '/ecosystem'
      path: '/ecosystem'
      fullPath: '/ecosystem'
      preLoaderRoute: typeof EcosystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/autopilot': {
      id: '/autopilot'
      path: '/autopilot'
      fullPath: '/autopilot'
      preLoaderRoute: typeof AutopilotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents': {
      id: '/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/$productId': {
      id: '/shop/$productId'
      path: '/$productId'
      fullPath: '/shop/$productId'
      preLoaderRoute: typeof ShopProductIdRouteImport
      parentRoute: typeof ShopRoute
    }
    '/checkout/success': {
      id: '/checkout/success'
      path: '/checkout/success'
      fullPath: '/checkout/success'
      preLoaderRoute: typeof CheckoutSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/callback': {
      id: '/checkout/callback'
      path: '/checkout/callback'
      fullPath: '/checkout/callback'
      preLoaderRoute: typeof CheckoutCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/revenue-ai': {
      id: '/admin/revenue-ai'
      path: '/revenue-ai'
      fullPath: '/admin/revenue-ai'
      preLoaderRoute: typeof AdminRevenueAiRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/public/paystack-webhook': {
      id: '/api/public/paystack-webhook'
      path: '/api/public/paystack-webhook'
      fullPath: '/api/public/paystack-webhook'
      preLoaderRoute: typeof ApiPublicPaystackWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/asset/$productId': {
      id: '/api/public/asset/$productId'
      path: '/api/public/asset/$productId'
      fullPath: '/api/public/asset/$productId'
      preLoaderRoute: typeof ApiPublicAssetProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminRevenueAiRoute: typeof AdminRevenueAiRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminRevenueAiRoute: AdminRevenueAiRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ShopRouteChildren {
  ShopProductIdRoute: typeof ShopProductIdRoute
}

const ShopRouteChildren: ShopRouteChildren = {
  ShopProductIdRoute: ShopProductIdRoute,
}

const ShopRouteWithChildren = ShopRoute._addFileChildren(ShopRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AgentsRoute: AgentsRoute,
  AutopilotRoute: AutopilotRoute,
  EcosystemRoute: EcosystemRoute,
  EliteRoute: EliteRoute,
  LoginRoute: LoginRoute,
  MealsRoute: MealsRoute,
  RegisterRoute: RegisterRoute,
  SettingsRoute: SettingsRoute,
  ShopRoute: ShopRouteWithChildren,
  WalletRoute: WalletRoute,
  CheckoutCallbackRoute: CheckoutCallbackRoute,
  CheckoutSuccessRoute: CheckoutSuccessRoute,
  ApiPublicPaystackWebhookRoute: ApiPublicPaystackWebhookRoute,
  ApiPublicAssetProductIdRoute: ApiPublicAssetProductIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
